version: '3.9'

services:
  backend:
    build:
      context: ./backend/node
    env_file:
      - ./backend/node/.env.docker
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
    depends_on:
      - db
    volumes:
      - ./backend/node:/app
      - /app/node_modules

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
